### ISSUE TITLE
Greetings. I am guessing this awesome library does not work on Windows? 

### ISSUE THREAD

**Issue by Tron-05** [advanced-stack/py-llm-core#16]
Greetings. I am guessing this awesome library does not work on Windows? It seems to have a Linux/Unix/MacOS path only.
Please advise, thank you : )

    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist: C:\Users\kajuk/.cache/py-llm-core/models\BakLLaVA-1-Q4_K_M.gguf

C:\_01Sync\Sync\001_Teaching\01_Courses\CSC444 DL\LLAVA Macbook only Test>

**Comment by paschembri** [comment]
Using pathlib here should resolve the issue on windows

model_path = os.path.join(MODELS_CACHE_DIR, self.name)

https://github.com/advanced-stack/py-llm-core/blob/e99f0930f448e7590bd6b6a0b90cc28605419e08/src/llm_core/llm/llama_cpp_compatible.py#L54

**Comment by paschembri** [comment]
Fixed in 2.8.5
