### ISSUE TITLE
Consider versioning mistralai in requirements.txt

### ISSUE THREAD

**Issue by AstraBert** [advanced-stack/py-llm-core#19]
**ISSUE DESCRIPTION**

When executing the code as reported in [this tutorial](https://advanced-stack.com/resources/multi-modalities-inference-using-mistral-ai-llava-bakllava-and-llama-cpp.html) after freshly installing `py-llm-core`, I get the following error: 

```
ModuleNotFoundError: No module named 'mistralai.models.chat_completion'
```

**POSSIBLE EXPLANATION**

This issue probably occurs as, according to what is reported in [this migration guide on `mistralai` repository](https://github.com/mistralai/client-python/blob/55b92b18b36ed909e5b56036d6c7962f66447067/MIGRATION.md), after the 1.0.0 version some methods were definitely dismissed.

**PROPOSED SOLUTION**

A workaround I found to make this work was to install mistralai via:

```
python3 -m pip install mistralai==0.*
```

This versioning could perhaps be added to your requirements.txt :)

**OS AND ENV SPECIFICITIES**

- Platform: tried both on Windows 10.0.22631 and Ubuntu 22.04.3
- Python: 3.11.9
- py-llm-core: 2.8.15

I'll be happy to open a PR if you feel it's the best way to deal with this issue!

Cheers,
Astra Clelia

**Comment by paschembri** [comment]
Thank you for the issue.

This is fixed in latest v3 release (the mistral client is the latest now)
